#!/usr/bin/perl
# M10 fixture: legacy codegen script — writes a Verilog module via heredoc.
use strict;
use warnings;

my $depth = 16;

open(my $fh, '>', 'gen_fifo.v') or die "cannot write gen_fifo.v: $!";
print $fh <<"EOV";
// Generated by gen_fifo.pl — do not edit.
module gen_fifo #(
    parameter DEPTH = $depth
) (
    input  wire clk,
    input  wire push,
    output wire full
);
  // body elided
endmodule
EOV
close($fh);
